name = "live"
main = "src/index.ts"
compatibility_date = "2023-10-25"
keep_vars = true

routes = [
	{ pattern = "live.hey.xyz", custom_domain = true }
]

[env.production.vars]
RELEASE = ""
LIVEPEER_API_KEY = ""
