name = "ws"
main = "src/index.ts"
compatibility_date = "2023-01-25"
keep_vars = true

routes = [
	{ pattern = "ws.hey.xyz", custom_domain = true }
]

[[queues.producers]]
  queue = "leafwatch-impressions"
	binding = "IMPRESSIONS_QUEUE"

[[queues.consumers]]
  queue = "leafwatch-impressions"
	max_batch_size = 30
  max_batch_timeout = 30

[env.production.vars]
CLICKHOUSE_REST_ENDPOINT = ""
