name = "leafwatch"
main = "src/index.ts"
compatibility_date = "2023-10-25"
keep_vars = true

routes = [
	{ pattern = "leafwatch.hey.xyz", custom_domain = true }
]

[env.production.vars]
RELEASE = ""
CLICKHOUSE_PASSWORD = ""
IPAPI_KEY = ""
