name = "stats"
main = "src/index.ts"
compatibility_date = "2023-10-25"
keep_vars = true

routes = [
	{ pattern = "stats.hey.xyz", custom_domain = true }
]

[placement]
mode = "smart"

[env.production.vars]
RELEASE = ""
CLICKHOUSE_PASSWORD = ""
