name = "metadata"
main = "src/index.ts"
compatibility_date = "2023-10-25"
keep_vars = true

routes = [
	{ pattern = "metadata.hey.xyz", custom_domain = true }
]

[placement]
mode = "smart"

[env.production.vars]
RELEASE = ""
IRYS_PRIVATE_KEY = ""
HUGGINGFACE_API_KEY = ""
