name = "preferences"
main = "src/index.ts"
compatibility_date = "2023-10-25"
keep_vars = true

routes = [
	{ pattern = "preferences.hey.xyz", custom_domain = true }
]

[env.production.vars]
RELEASE = ""
SUPABASE_KEY = ""
