name = "preferences"
main = "src/index.ts"
compatibility_date = "2023-10-25"
keep_vars = true

routes = [
	{ pattern = "preferences.hey.xyz", custom_domain = true }
]

kv_namespaces = [
  { binding = "PREFERENCES", id = "0c2df8f66fcd4704a4463e3db73471ca", preview_id = "0c2df8f66fcd4704a4463e3db73471ca" }
]

[env.production.vars]
RELEASE = ""
SUPABASE_KEY = ""
