name = "zora"
main = "src/index.ts"
compatibility_date = "2023-01-25"
keep_vars = true

routes = [
	{ pattern = "zora.lenster.xyz", custom_domain = true }
]

[env.production.vars]
SENTRY_DSN = ""
RELEASE = ""
