name: Docker Build and Push

inputs:
  GITHUB_TOKEN:
    description: GitHub token
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm 🌸
      uses: pnpm/action-setup@v2.2.4

    - name: Setup node 🍀
      uses: actions/setup-node@v3
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        check-latest: true
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: Bootstrap 📦
      run: script/bootstrap
