name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm 🌸
        uses: pnpm/action-setup@v2.2.4

      - name: Setup node 🍀
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Bootstrap 📦
        run: script/bootstrap

      - name: Typecheck 🔡
        run: pnpm typecheck:affected

      - name: Lint 🪩
        run: pnpm lint:affected

      - name: Prettier ✨
        run: pnpm prettier:affected

      - name: Build 🎁
        run: pnpm build

      - name: Run Tests 🧪
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET: ${{ secrets.SECRET }}
          EVER_ACCESS_KEY: ${{ secrets.EVER_ACCESS_KEY }}
          EVER_ACCESS_SECRET: ${{ secrets.EVER_ACCESS_SECRET }}
          LENS_IPFS_AUTH_KEY: ${{ secrets.LENS_IPFS_AUTH_KEY }}
          CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          IRYS_PRIVATE_KEY: ${{ secrets.IRYS_PRIVATE_KEY }}
          LIVEPEER_API_KEY: ${{ secrets.LIVEPEER_API_KEY }}
        run: pnpm test:e2e
