name: Cron - DB Backup

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  downgrade:
    name: Backup
    runs-on: ubuntu-latest
    steps:
      - name: Backup Postgres DB and Push
        uses: kodermax/database-backup-action@main
        with:
          database_username: ${{ secrets.DB_USER }}
          database_password: ${{ secrets.DB_PASS }}
          database_name: ${{ secrets.DB_NAME }}
          database_host: roundhouse.proxy.rlwy.net:39560
          database_opts: pg_dump
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          storage_bucket: ${{ secrets.AWS_S3_BUCKET }}
          storage_region: eu-west-2
