name: Cron Jobs

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  cleanup-postgres:
    name: Cleanup Postgres
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Postgres
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Referer: https://hey.xyz" \
            -d '{"secret": "'"$SECRET"'"}' \
            https://api.hey.xyz/internal/cron/cleanPostgres

  cleanup-clickhouse:
    name: Cleanup Clickhouse
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Clickhouse
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Referer: https://hey.xyz" \
            -d '{"secret": "'"$SECRET"'"}' \
            https://api.hey.xyz/internal/cron/cleanClickhouse

  downgrade-profiles:
    name: Downgrade Profiles
    runs-on: ubuntu-latest
    steps:
      - name: Downgrade Profiles
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Referer: https://hey.xyz" \
            -d '{"secret": "'"$SECRET"'"}' \
            https://api.hey.xyz/internal/cron/downgradePro
