name: Cron - Cleanup DB

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup DB
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Referer: https://hey.xyz" \
            -d '{"secret": "'"$SECRET"'"}' \
            https://api.hey.xyz/internal/cleanup/db
