name: Cron - Downgrade Profiles

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  downgrade:
    name: Downgrade
    runs-on: ubuntu-latest
    steps:
      - name: Downgrade Profiles
        env:
          WORKER_SECRET: ${{ secrets.WORKER_SECRET }}
        run: |
          curl -X DELETE \
            -d '{"secret": "'"$WORKER_SECRET"'"}' \
            https://internal.hey.xyz/pro/downgradeProfiles
