name: Deploy Docker Images

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v4

      - name: Set up QEMU 🐳
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx 🐳
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub 🔑
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Web image 🚀
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web:latest

      - name: Build and push API image 🚀
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api:latest

      - name: Build and push OG image 🚀
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/og/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/og:latest
