name: Deploy API Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v4

      - name: Set up QEMU 🐳
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx 🐳
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub 🔑
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image 🚀
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api:latest

      - name: Trigger API Deployment 🚀
        env:
          SECRET: ${{ secrets.SECRET }}
          SERVICE_ID: '4a2a1bfb-e499-4c71-bf7f-d9ad47443c31'
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Referer: https://hey.xyz" \
            -d '{"secret": "'"$SECRET"'", "serviceId": "'"$SERVICE_ID"'"}' \
            https://api.hey.xyz/internal/railway/triggerDeployments
