name: Deploy Docker Images

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  web:
    name: Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v4

      - name: Build and push Web image 🚀
        uses: ./.github/actions/docker
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          image_name: web
          docker_file: ./apps/web/Dockerfile

  api:
    name: API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v4

      - name: Build and push API image 🚀
        uses: ./.github/actions/docker
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE_NAME: api
          DOCKER_FILE: ./apps/api/Dockerfile

      - name: Trigger API Deployment 🚀
        uses: indiesdev/curl@v1.1
        with:
          url: https://api.hey.xyz/internal/railway/triggerDeployments
          method: 'POST'
          body: '{ "secret": "${{ secrets.SECRET }}", "serviceId": "4a2a1bfb-e499-4c71-bf7f-d9ad47443c31" }'
          headers: '{ "Content-Type": "application/json", "Referer": "https://hey.xyz" }'

  og:
    name: OG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v4

      - name: Build and push OG image 🚀
        uses: ./.github/actions/docker
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE_NAME: og
          DOCKER_FILE: ./apps/og/Dockerfile
