name: PR Title Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate:
    name: PR Title Validation
    runs-on: ubuntu-latest
    steps:
      - name: PR Title Validation
        uses:  ytanikin/PRConventionalCommits@1.1.0
        with:
          task_types: '["feat","fix","docs","refactor","cleanup","chore","revert"]'
          add_label: 'false'
